# Site settings
title: Joe Letchford
version: "v2"
description: ""
# delete "joe-letchford" when working locally
baseurl: "joeletchford" # the subpath of your site, e.g. /blog
url: "joeletchford.com" # the base hostname & protocol for your site
email: "joeletchford@gmail.com"
tele: "+1.804.815.5044"
social:
  - title: drobble
    url: https://www.dribbble.com/joeletchford
  - title: stagram
    url: https://www.instagram.com/joeletchford
  - title: twotter
    url: https://www.twitter.com/joeletchford

# Tachyons Version
tv: "4.7.0"

# Build settings
markdown: kramdown

# Exclude this stuff
exclude: [node_modules, gulpfile.js]

# Gems
gems:
  - jekyll-seo-tag

permalink: /:title.html
sass:
  load_paths:
    - node_modules
